# -----------------------------------------------------------------
# 🤖 Botub AI & AyTech Solution - Official Funding Configuration
# -----------------------------------------------------------------
github: [AyTech-Solution]
custom: [
 "https://upilinks.in/payment-link/upi1042559340",
"https://instagram.com/aytech_solution"
]
